/* by Capitanul burcea,alex */
module.exports = {
  manele: {
    label: 'Manele',
    emoji: 'radio',
    description: 'Manele live, vechi si noi',
    search: { tag: 'manele', countrycode: 'RO' },
    urls: [
      'http://asculta.radioxnet.ro:8888/listen.pls',
      'http://radiopromanele.zapto.org:8000/listen.pls',
      'http://b.fmradiomanele.ro:8044/listen.pls',
      'http://a.fmradiomanele.ro:8054/listen.pls',
    ],
  },
  lautareasca: {
    label: 'Lautareasca',
    emoji: 'radio',
    description: 'Lautareasca, taraf si petrecere',
    search: { tag: 'lautareasca', countrycode: 'RO' },
    urls: [
      'http://live.radiolautaru.ro:9000/stream',
      'http://asculta.radiotaraf.com:7100/listen.pls',
    ],
  },
  populara: {
    label: 'Populara',
    emoji: 'radio',
    description: 'Muzica populara romaneasca',
    search: { tag: 'populara', countrycode: 'RO' },
    urls: [
      'http://petrecere.fmradiomanele.ro:8123/listen.pls',
      'http://live.radiolautaru.ro:9000/stream',
    ],
  },
  colinde: {
    label: 'Colinde',
    emoji: 'radio',
    description: 'Colinde si muzica de sarbatori',
    search: { name: 'colinde', countrycode: 'RO' },
    urls: [
      'http://radiocolinde.ro',
      'http://radio-focus.ro',
    ],
  },
  dance: {
    label: 'Dance',
    emoji: 'radio',
    description: 'Dance, club si party hits',
    search: { tag: 'dance', countrycode: 'RO' },
    urls: [],
  },
  house: {
    label: 'House',
    emoji: 'radio',
    description: 'House, tech-house si club',
    search: { tag: 'house' },
    urls: [],
  },
  edm: {
    label: 'EDM',
    emoji: 'radio',
    description: 'Electronic dance music live',
    search: { tag: 'edm' },
    urls: [],
  },
  chill: {
    label: 'Chill',
    emoji: 'radio',
    description: 'Chillout, lounge si relax',
    search: { tag: 'chillout' },
    urls: [],
  },
  lofi: {
    label: 'Lo-Fi',
    emoji: 'radio',
    description: 'Lo-fi beats si focus',
    search: { tag: 'lofi' },
    urls: [],
  },
  hiphop: {
    label: 'Hip-Hop',
    emoji: 'radio',
    description: 'Hip-hop si rap',
    search: { tag: 'hiphop' },
    urls: [],
  },
  trap: {
    label: 'Trap',
    emoji: 'radio',
    description: 'Trap, drill si urban',
    search: { tag: 'trap' },
    urls: [],
  },
  pop: {
    label: 'Pop',
    emoji: 'radio',
    description: 'Pop hits internationale',
    search: { tag: 'pop' },
    urls: [],
  },
  romanian: {
    label: 'Romania',
    emoji: 'radio',
    description: 'Posturi romanesti populare',
    search: { countrycode: 'RO' },
    urls: [],
  },
  europa: {
    label: 'Europa',
    emoji: 'radio',
    description: 'Top radio Europa',
    search: { tag: 'top40' },
    urls: [],
  },
  rock: {
    label: 'Rock',
    emoji: 'radio',
    description: 'Rock clasic si modern',
    search: { tag: 'rock' },
    urls: [],
  },
  metal: {
    label: 'Metal',
    emoji: 'radio',
    description: 'Metal si hard rock',
    search: { tag: 'metal' },
    urls: [],
  },
  jazz: {
    label: 'Jazz',
    emoji: 'radio',
    description: 'Jazz si smooth jazz',
    search: { tag: 'jazz' },
    urls: [],
  },
  blues: {
    label: 'Blues',
    emoji: 'radio',
    description: 'Blues live radio',
    search: { tag: 'blues' },
    urls: [],
  },
  reggae: {
    label: 'Reggae',
    emoji: 'radio',
    description: 'Reggae si dancehall',
    search: { tag: 'reggae' },
    urls: [],
  },
  latino: {
    label: 'Latino',
    emoji: 'radio',
    description: 'Latino, reggaeton si bachata',
    search: { tag: 'latino' },
    urls: [],
  },
  kpop: {
    label: 'K-Pop',
    emoji: 'radio',
    description: 'K-pop si Asian hits',
    search: { tag: 'kpop' },
    urls: [],
  },
  anime: {
    label: 'Anime',
    emoji: 'radio',
    description: 'Anime, J-pop si OST',
    search: { tag: 'anime' },
    urls: [],
  },
  gaming: {
    label: 'Gaming',
    emoji: 'radio',
    description: 'Gaming, synthwave si soundtrack',
    search: { tag: 'gaming' },
    urls: [],
  },
  news: {
    label: 'News',
    emoji: 'radio',
    description: 'Stiri si talk radio',
    search: { tag: 'news', countrycode: 'RO' },
    urls: [],
  },
};
